### ISSUE TITLE
Bulk RNA seq

### ISSUE THREAD

**Issue by mdanb** [cellgeni/batchbench#21]
Do the batch correction methods in batchbench work for Bulk RNA seq (instead of single cell)?

**Comment by rubenchazarra** [comment]
Hi @mdanb, 
The overall method requires the input to be a SingleCellExperiment object. I believe you can generate a SCE object with bulk RNA-Seq data, although some of the batch correction methods included have been specifically developed for scRNA-seq data, and account for the particularities of this type of data. This is why the behaviour of these methods can be unpredictable with bulk RNA-seq data. 
Nonetheless, BatchBench also includes some batch-correction methods initially designed for microarray and bulkRNA-Seq data (Limma, ComBat), in which case the method could work if you pack your data into an SCE object.

**Comment by mdanb** [comment]
@rubenchazarra "BatchBench also includes some batch-correction methods initially designed for microarray and bulkRNA-Seq data" 
which ones?

**Comment by rubenchazarra** [comment]
@mdanb These are Limma and ComBat
