### ISSUE TITLE
metadata.txt Format

### ISSUE THREAD

**Issue by jefferyUstc** [cellgeni/batchbench#9]
Hi, The work , BatchBench,  seems fantastic, But In the README, the format of metadata.txt is confused, suppose I have datasets A (A.rds), B (B.rds), then metadata.txt should be how?

**Comment by rubenchazarra** [comment]
Hi @jefferyUstc,
Sorry for this late response. The metadata file should include a list of the datasets base names, without suffixes. In you example this would be: 
A
B
And the path to this dataset list text file should be specified in the `nextflow.config` file under the __dataset_list__ parameter.
